# Generated by Django 4.0.3 on 2022-04-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_name', models.CharField(max_length=20)),
                ('nationality_shortcut', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('nationality_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formule.nationality', verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racer_name', models.CharField(max_length=20)),
                ('racer_surname', models.CharField(max_length=20)),
                ('racer_rank', models.IntegerField(max_length=200)),
                ('racer_formule_model', models.CharField(max_length=50)),
                ('racer_born', models.DateTimeField(verbose_name='date published')),
                ('nationality_shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formule.nationality', verbose_name='Nationality shortcut')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formule.team', verbose_name='Team name')),
            ],
        ),
        migrations.CreateModel(
            name='Grand_prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix_lenght', models.IntegerField(help_text='Enter lenght in KM', max_length=30)),
                ('grand_prix_max_racers', models.IntegerField(max_length=20)),
                ('grand_prix_took_place', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('nationality_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formule.nationality', verbose_name='Nationality')),
            ],
        ),
    ]
