# Generated by Django 4.0.3 on 2022-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_lenght',
            field=models.IntegerField(help_text='Enter lenght in KM', max_length=30, verbose_name='Track lenght'),
        ),
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_max_racers',
            field=models.IntegerField(max_length=20, verbose_name='Max. Racers'),
        ),
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_took_place',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Took place'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality_name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality_shortcut',
            field=models.CharField(max_length=3, verbose_name='Shortcut'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_born',
            field=models.DateField(verbose_name='Born date'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_formule_model',
            field=models.CharField(max_length=50, verbose_name='Formule model'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_rank',
            field=models.IntegerField(max_length=200, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_surname',
            field=models.CharField(max_length=20, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='sesion_description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
