# Generated by Django 4.0.3 on 2022-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0002_alter_grand_prix_grand_prix_lenght_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grand_prix',
            options={'ordering': ['nationality_name']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['nationality_name']},
        ),
        migrations.AlterModelOptions(
            name='racer',
            options={'ordering': ['racer_name']},
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['sesion_year']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
        migrations.AddField(
            model_name='sesion',
            name='sesion_year',
            field=models.IntegerField(default=1950, max_length=4, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_lenght',
            field=models.IntegerField(default=3100, help_text='Enter lenght in Metres', max_length=30, verbose_name='Track lenght'),
        ),
    ]
