# Generated by Django 4.0.3 on 2022-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0003_alter_grand_prix_options_alter_nationality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_lenght',
            field=models.IntegerField(default=3100, help_text='Enter lenght in Metres', verbose_name='Track lenght'),
        ),
        migrations.AlterField(
            model_name='grand_prix',
            name='grand_prix_max_racers',
            field=models.IntegerField(verbose_name='Max. Racers'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='racer_rank',
            field=models.IntegerField(verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='sesion_year',
            field=models.IntegerField(default=1950, verbose_name='Year'),
        ),
    ]
