# Generated by Django 4.0.3 on 2022-04-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0006_alter_grand_prix_grand_prix_lenght'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grand_prix',
            options={'ordering': ['grand_prix_lenght']},
        ),
    ]
