# Generated by Django 4.0.3 on 2022-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0009_alter_grand_prix_options_grand_prix_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sesion_description',
            field=models.TextField(max_length=750, verbose_name='Description'),
        ),
    ]
