# Generated by Django 4.0.3 on 2022-06-04 19:33

from django.db import migrations, models
import formule.models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0010_alter_sesion_sesion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=formule.models.pic_nat, verbose_name='Nationality flag'),
        ),
    ]
