# Generated by Django 4.0.3 on 2022-06-04 19:54

from django.db import migrations, models
import formule.models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0011_nationality_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=formule.models.pic_rac, verbose_name='Photo'),
        ),
    ]
