# Generated by Django 4.0.3 on 2022-06-04 21:02

from django.db import migrations, models
import formule.models


class Migration(migrations.Migration):

    dependencies = [
        ('formule', '0012_racer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=formule.models.pic_team, verbose_name='Team badge'),
        ),
    ]
